minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - fast-xml-parser
  - sharp
  - unrs-resolver
  - vue-demi

overrides:
  chrono-node@<2.2.4: '>=2.2.4'
